### ISSUE TITLE
UI service is created as a NodePort even if you specify ClusterIP in values.yaml

### ISSUE THREAD

**Issue by zanloy** [kubevious/helm#18]
When I tried to install from the official helm repo, the ingress never worked so I downloaded the entire chart and found the following. It seems like if the ingress.type is ClusterIP then we would not want to return NodePort as the type for the service. After fixing this to us `ne` instead of `eq`, it installed correctly and I was able to use the ingress.

https://github.com/kubevious/helm/blob/c9091cbb69e56b39cfd3ad3b2d3c7e129200dd6e/kubernetes/templates/_helpers.tpl#L196

**Comment by rubenhak** [comment]
@zanloy, could you provide details on your ingress setup? Did you override any of the parameters? What kind of ingress? What kind of cluster?

**Comment by zanloy** [comment]
I'm using Kubernetes (v1.15), Docker-CE (v20.10), and nginx-ingress-controller (v0.33). But regardless of those, in the values.yaml, it says the service is supposed to be type ClusterIP but without making the above modification, it created the Service as a NodePort which then didn't work with the ingress.

**Comment by zanloy** [comment]
Oh, I forgot to answer what params I overrode.
```yaml
cluster: prod
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/auth-signin: "https://oauth.prod.example.com/oauth2/start?rd=https://$host$request_uri$is_args$args"
    nginx.ingress.kubernetes.io/auth-url: "https://oauth.prod.example.com/oauth/auth"
    nginx.ingress.kubernetes.io/enable-cors: "true"
  hosts:
    - host: "kubevious.prod.example.com"
      paths: ["/"]
  tls: []
```
