### ISSUE TITLE
livenessProbe problem with Collector

### ISSUE THREAD

**Issue by Ra-Amine** [kubevious/helm#27]
Hello,

When I install helm chart in my cluster, collector pod can start and stay in CrashLoopBackOff state .

After investigation, periodSeconds in livenessProbe section is too short and is not editable from chart values, so I have to manually edit the deployment to increase this value.

Defaults values: 
```
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: http
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: kubevious
    ports:
    - containerPort: 4002
      name: http
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: http
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
```
Is it possible to add the possibility to control the livenessProbe and readinessProbe from the values ​​of the helm charts?

Best regards

**Comment by rubenhak** [comment]
@Ra-Amine, thanks for submitting this request. This request sounds reasonable. Would you like to contribute to the project by adding that support to the chart? 

Do you have a particularly large cluster? Which version are you using right now?

What do you think about a structure like this in the [values.yaml](https://github.com/kubevious/helm/blob/master/kubernetes/values.yaml)?
```yaml
collector:
  health:
    readinessProbe:
      periodSeconds: 10
    livenessProbe:
      periodSeconds: 10
```

If you decide to submit a PR with your changes, please also include the entries in the [README.md docs](https://github.com/kubevious/helm/blob/master/README.md#%EF%B8%8F-configuration)

The chart is here: https://github.com/kubevious/helm/tree/master/kubernetes

Thanks
